# Generated by Django 6.0.7 on 2026-07-28 13:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('feature_flags', '0001_initial'),
        ('organizations', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='featureflag',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Criado por'),
        ),
        migrations.AddField(
            model_name='featureflag',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='feature_flags', to='auth.group', verbose_name='Grupos'),
        ),
        migrations.AddField(
            model_name='featureflag',
            name='users',
            field=models.ManyToManyField(blank=True, help_text='Users for whom this flag is active (waffle compatibility)', related_name='feature_flags_direct', to=settings.AUTH_USER_MODEL, verbose_name='Usuários'),
        ),
        migrations.AddField(
            model_name='featureflagassignment',
            name='flag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='feature_flags.featureflag', verbose_name='Flag'),
        ),
        migrations.AddField(
            model_name='featureflagassignment',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feature_flags', to='organizations.organization', verbose_name='Organização'),
        ),
        migrations.AddField(
            model_name='featureflagassignment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feature_flags', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AddIndex(
            model_name='featureflag',
            index=models.Index(fields=['code'], name='feature_fla_code_534c4c_idx'),
        ),
        migrations.AddIndex(
            model_name='featureflag',
            index=models.Index(fields=['is_active'], name='feature_fla_is_acti_f68ec0_idx'),
        ),
        migrations.AddIndex(
            model_name='featureflagassignment',
            index=models.Index(fields=['flag', 'organization', 'is_active'], name='feature_fla_flag_id_aaebdc_idx'),
        ),
        migrations.AddIndex(
            model_name='featureflagassignment',
            index=models.Index(fields=['flag', 'user', 'is_active'], name='feature_fla_flag_id_9e6731_idx'),
        ),
    ]
