# Generated by Django 6.0.7 on 2026-07-27 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('key_hash', models.CharField(max_length=255, unique=True, verbose_name='Key Hash')),
                ('prefix', models.CharField(max_length=12, verbose_name='Prefix')),
                ('scopes', models.JSONField(blank=True, default=list, verbose_name='Scopes')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='Último Uso')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Expira em')),
            ],
            options={
                'verbose_name': 'API Key',
                'verbose_name_plural': 'API Keys',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PersonalAccessToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('token_hash', models.CharField(max_length=255, unique=True, verbose_name='Token Hash')),
                ('scopes', models.JSONField(blank=True, default=list, verbose_name='Scopes')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Expira em')),
            ],
            options={
                'verbose_name': 'Personal Access Token',
                'verbose_name_plural': 'Personal Access Tokens',
            },
        ),
        migrations.CreateModel(
            name='ServiceAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('token_hash', models.CharField(max_length=255, unique=True, verbose_name='Token Hash')),
                ('permissions', models.JSONField(blank=True, default=list, verbose_name='Permissões')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Service Account',
                'verbose_name_plural': 'Service Accounts',
            },
        ),
    ]
