# Generated by Django 6.0.7 on 2026-07-27 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('stripe_invoice_id', models.CharField(blank=True, max_length=255, verbose_name='Stripe Invoice ID')),
                ('amount_cents', models.PositiveIntegerField(verbose_name='Valor (centavos)')),
                ('status', models.CharField(default='pending', max_length=50, verbose_name='Status')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Pago em')),
                ('due_date', models.DateTimeField(blank=True, null=True, verbose_name='Data de Vencimento')),
            ],
            options={
                'verbose_name': 'Fatura',
                'verbose_name_plural': 'Faturas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('stripe_price_id', models.CharField(blank=True, max_length=255, verbose_name='Stripe Price ID')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('features', models.JSONField(blank=True, default=dict, verbose_name='Funcionalidades')),
                ('limits', models.JSONField(blank=True, default=dict, verbose_name='Limites')),
                ('price_cents', models.PositiveIntegerField(default=0, verbose_name='Preço (centavos)')),
                ('billing_cycle', models.IntegerField(choices=[(1, 'Mensal'), (2, 'Trimestral'), (3, 'Semestral'), (4, 'Anual')], default=1, verbose_name='Ciclo de Cobrança')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Ordem de Exibição')),
            ],
            options={
                'verbose_name': 'Plano',
                'verbose_name_plural': 'Planos',
                'ordering': ['display_order', 'price_cents'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=255, verbose_name='Stripe Subscription ID')),
                ('stripe_customer_id', models.CharField(blank=True, max_length=255, verbose_name='Stripe Customer ID')),
                ('status', models.IntegerField(choices=[(1, 'Ativa'), (2, 'Atrasada'), (3, 'Cancelada'), (4, 'Em teste'), (5, 'Pausada'), (6, 'Não paga')], default=1, verbose_name='Status')),
                ('current_period_start', models.DateTimeField(blank=True, null=True, verbose_name='Início do Período')),
                ('current_period_end', models.DateTimeField(blank=True, null=True, verbose_name='Fim do Período')),
                ('cancel_at_period_end', models.BooleanField(default=False, verbose_name='Cancelar no fim do período')),
                ('trial_end', models.DateTimeField(blank=True, null=True, verbose_name='Fim do Teste')),
            ],
            options={
                'verbose_name': 'Assinatura',
                'verbose_name_plural': 'Assinaturas',
                'ordering': ['-created_at'],
            },
        ),
    ]
