# Generated by Django 6.0.7 on 2026-07-28 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('task_path', models.CharField(max_length=500, verbose_name='Task Path')),
                ('status', models.IntegerField(choices=[(1, 'Pendente'), (2, 'Em execução'), (3, 'Concluído'), (4, 'Falhou'), (5, 'Retentando'), (6, 'Dead Letter')], default=1, verbose_name='Status')),
                ('priority', models.IntegerField(default=5, verbose_name='Prioridade')),
                ('retries', models.PositiveIntegerField(default=0, verbose_name='Retries')),
                ('max_retries', models.PositiveIntegerField(default=3, verbose_name='Max Retries')),
                ('last_error', models.TextField(blank=True, verbose_name='Último Erro')),
                ('scheduled_at', models.DateTimeField(blank=True, null=True, verbose_name='Agendado')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Início')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Conclusão')),
            ],
            options={
                'verbose_name': 'Job',
                'verbose_name_plural': 'Jobs',
                'ordering': ['priority', '-created_at'],
            },
        ),
    ]
