# Generated by Django 6.0.7 on 2026-07-28 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='organizations.organization', verbose_name='Organização'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['status', 'priority'], name='jobs_job_status_007c84_idx'),
        ),
    ]
