# Generated by Django 6.0.7 on 2026-07-27 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Integration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('integration_type', models.CharField(max_length=100, verbose_name='Tipo')),
                ('credentials_encrypted', models.BinaryField(blank=True, null=True, verbose_name='Credenciais')),
                ('status', models.CharField(default='active', max_length=50, verbose_name='Status')),
                ('last_health_check', models.DateTimeField(blank=True, null=True, verbose_name='Último Health Check')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadados')),
            ],
            options={
                'verbose_name': 'Integração',
                'verbose_name_plural': 'Integrações',
            },
        ),
        migrations.CreateModel(
            name='IntegrationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('action', models.CharField(max_length=255, verbose_name='Ação')),
                ('request_data', models.JSONField(default=dict, verbose_name='Request')),
                ('response_data', models.JSONField(default=dict, verbose_name='Response')),
                ('status', models.CharField(max_length=50, verbose_name='Status')),
                ('duration_ms', models.PositiveIntegerField(default=0, verbose_name='Duração')),
                ('error_message', models.TextField(blank=True, verbose_name='Erro')),
            ],
            options={
                'verbose_name': 'Log de Integração',
                'verbose_name_plural': 'Logs de Integração',
                'ordering': ['-created_at'],
            },
        ),
    ]
