# Generated by Django 6.0.7 on 2026-07-28 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('integrations', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='integration',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integrations', to='organizations.organization', verbose_name='Organização'),
        ),
        migrations.AddField(
            model_name='integrationlog',
            name='integration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='integrations.integration', verbose_name='Integração'),
        ),
        migrations.AddIndex(
            model_name='integration',
            index=models.Index(fields=['organization', 'status'], name='integration_organiz_aec7ec_idx'),
        ),
    ]
