# Generated by Django 6.0.7 on 2026-07-28 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuotaDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('code', models.CharField(max_length=255, unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('unit', models.CharField(max_length=100, verbose_name='Unidade')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('default_limit', models.PositiveIntegerField(default=0, verbose_name='Limite Padrão')),
            ],
            options={
                'verbose_name': 'Definição de Quota',
                'verbose_name_plural': 'Definições de Quotas',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='QuotaAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('limit', models.PositiveIntegerField(verbose_name='Limite')),
                ('used', models.PositiveIntegerField(default=0, verbose_name='Usado')),
                ('period_start', models.DateField(verbose_name='Início do Período')),
                ('period_end', models.DateField(verbose_name='Fim do Período')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quota_allocations', to='organizations.organization', verbose_name='Organização')),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='quotas.quotadefinition', verbose_name='Definição')),
            ],
            options={
                'verbose_name': 'Alocação de Quota',
                'verbose_name_plural': 'Alocações de Quotas',
                'indexes': [models.Index(fields=['organization', 'definition'], name='quotas_quot_organiz_3007a0_idx')],
                'unique_together': {('organization', 'definition', 'period_start')},
            },
        ),
    ]
