# Generated by Django 6.0.7 on 2026-07-31 21:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('organizations', '0002_initial'),
        ('radar_templates', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('title', models.CharField(max_length=255, verbose_name='Titulo')),
                ('description', models.TextField(blank=True, verbose_name='Descricao')),
                ('status', models.CharField(choices=[('a_fazer', 'A fazer'), ('em_andamento', 'Em andamento'), ('concluida', 'Concluida'), ('aguardando_cliente', 'Aguardando cliente'), ('aguardando_terceiro', 'Aguardando terceiro'), ('bloqueada', 'Bloqueada'), ('cancelada', 'Cancelada')], default='a_fazer', max_length=25, verbose_name='Status')),
                ('priority', models.CharField(choices=[('low', 'Baixa'), ('medium', 'Media'), ('high', 'Alta'), ('urgent', 'Urgente')], default='medium', max_length=10, verbose_name='Prioridade')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='Categoria')),
                ('assigned_to', models.CharField(blank=True, max_length=150, verbose_name='Responsavel (nome)')),
                ('due_date', models.DateTimeField(blank=True, null=True, verbose_name='Prazo')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Concluida em')),
                ('recurrence_rule', models.JSONField(blank=True, default=dict, verbose_name='Regra de recorrencia')),
                ('portal_visible', models.BooleanField(default=False, verbose_name='Visivel no portal')),
                ('portal_instructions', models.TextField(blank=True, verbose_name='Instrucoes para o cliente')),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='radar_templates.templateapplication', verbose_name='Aplicacao de origem')),
                ('assigned_to_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Responsavel')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='radar_tasks', to='clients.clientcompany', verbose_name='Cliente')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='clients.department', verbose_name='Departamento')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='organizations.organization', verbose_name='Organização')),
                ('parent_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='radar_tasks.task', verbose_name='Tarefa-mae')),
                ('recurrence_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurrence_children', to='radar_tasks.task', verbose_name='Serie recorrente (origem)')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewing_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Revisor')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_tasks', to='radar_templates.template', verbose_name='Template de origem')),
            ],
            options={
                'verbose_name': 'Tarefa',
                'verbose_name_plural': 'Tarefas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('text', models.CharField(max_length=255, verbose_name='Texto')),
                ('done', models.BooleanField(default=False, verbose_name='Concluido')),
                ('required', models.BooleanField(default=False, verbose_name='Obrigatorio')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='organizations.organization', verbose_name='Organização')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist', to='radar_tasks.task', verbose_name='Tarefa')),
            ],
            options={
                'verbose_name': 'Item de checklist',
                'verbose_name_plural': 'Itens de checklist',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TaskComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('user_name', models.CharField(blank=True, max_length=150, verbose_name='Autor (nome)')),
                ('content', models.TextField(verbose_name='Conteudo')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='organizations.organization', verbose_name='Organização')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='radar_tasks.task', verbose_name='Tarefa')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Comentario',
                'verbose_name_plural': 'Comentarios',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskDependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('blocking_type', models.CharField(choices=[('blocking', 'Bloqueante'), ('informational', 'Informativa')], default='blocking', max_length=20, verbose_name='Tipo')),
                ('depends_on', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependents', to='radar_tasks.task', verbose_name='Depende de')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='organizations.organization', verbose_name='Organização')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencies', to='radar_tasks.task', verbose_name='Tarefa')),
            ],
            options={
                'verbose_name': 'Dependencia de tarefa',
                'verbose_name_plural': 'Dependencias de tarefa',
            },
        ),
        migrations.CreateModel(
            name='TaskFollower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Membro')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='organizations.organization', verbose_name='Organização')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='radar_tasks.task', verbose_name='Tarefa')),
            ],
            options={
                'verbose_name': 'Seguidor de tarefa',
                'verbose_name_plural': 'Seguidores de tarefa',
            },
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['organization', 'status'], name='radar_tasks_organiz_8fda85_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['organization', 'due_date'], name='radar_tasks_organiz_8958c8_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['organization', 'client'], name='radar_tasks_organiz_511325_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='taskdependency',
            unique_together={('task', 'depends_on')},
        ),
        migrations.AlterUniqueTogether(
            name='taskfollower',
            unique_together={('task', 'member')},
        ),
    ]
