# Generated by Django 6.0.7 on 2026-07-27 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(max_length=255, verbose_name='Content Type')),
                ('object_id', models.CharField(max_length=255, verbose_name='Object ID')),
                ('content', models.TextField(verbose_name='Conteúdo')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadados')),
                ('indexed_at', models.DateTimeField(auto_now=True, verbose_name='Indexado em')),
            ],
            options={
                'verbose_name': 'Índice de Busca',
                'verbose_name_plural': 'Índices de Busca',
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='search_sear_content_85ca57_idx')],
                'unique_together': {('content_type', 'object_id')},
            },
        ),
    ]
