# Generated by Django 6.0.7 on 2026-07-31 22:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_initial'),
        ('storage', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('type', models.CharField(max_length=50, verbose_name='Tipo')),
                ('format', models.CharField(default='csv', max_length=10, verbose_name='Formato')),
                ('filters', models.JSONField(blank=True, default=dict, verbose_name='Filtros')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('completed', 'Concluida'), ('failed', 'Falhou')], default='pending', max_length=20, verbose_name='Status')),
                ('error_message', models.TextField(blank=True, verbose_name='Erro')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='organizations.organization', verbose_name='Organização')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='export_jobs', to=settings.AUTH_USER_MODEL, verbose_name='Solicitado por')),
                ('stored_object', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='storage.storedobject', verbose_name='Arquivo')),
            ],
            options={
                'verbose_name': 'Exportacao',
                'verbose_name_plural': 'Exportacoes',
                'ordering': ['-created_at'],
            },
        ),
    ]
