# Generated by Django 6.0.7 on 2026-07-28 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsageRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('metric_type', models.IntegerField(choices=[(1, 'Tokens IA'), (2, 'Requisições IA'), (3, 'Requisições API'), (4, 'Upload de Arquivos'), (5, 'Download de Arquivos'), (6, 'Bytes Armazenados')], verbose_name='Tipo de Métrica')),
                ('value', models.PositiveIntegerField(verbose_name='Valor')),
                ('unit', models.CharField(max_length=100, verbose_name='Unidade')),
                ('period', models.DateField(verbose_name='Período')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadados')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_records', to='organizations.organization', verbose_name='Organização')),
            ],
            options={
                'verbose_name': 'Registro de Uso',
                'verbose_name_plural': 'Registros de Uso',
                'ordering': ['-created_at'],
            },
        ),
    ]
