# Generated by Django 6.0.7 on 2026-07-28 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEndpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('url', models.URLField(max_length=2000, verbose_name='URL')),
                ('secret_encrypted', models.BinaryField(blank=True, null=True, verbose_name='Secret')),
                ('events', models.JSONField(blank=True, default=list, verbose_name='Eventos')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_endpoints', to='organizations.organization', verbose_name='Organização')),
            ],
            options={
                'verbose_name': 'Webhook Endpoint',
                'verbose_name_plural': 'Webhook Endpoints',
            },
        ),
        migrations.CreateModel(
            name='WebhookDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('event_type', models.CharField(max_length=255, verbose_name='Tipo de Evento')),
                ('payload', models.JSONField(default=dict, verbose_name='Payload')),
                ('status', models.CharField(default='pending', max_length=50, verbose_name='Status')),
                ('attempts', models.PositiveIntegerField(default=0, verbose_name='Tentativas')),
                ('response_code', models.PositiveIntegerField(blank=True, null=True, verbose_name='Código de Resposta')),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True, verbose_name='Última Tentativa')),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='webhooks.webhookendpoint', verbose_name='Endpoint')),
            ],
            options={
                'verbose_name': 'Entrega de Webhook',
                'verbose_name_plural': 'Entregas de Webhooks',
                'ordering': ['-created_at'],
            },
        ),
    ]
