# Generated by Django 6.0.7 on 2026-07-27 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('system_prompt', models.TextField(verbose_name='System Prompt')),
                ('model_id', models.CharField(default='gpt-4o', max_length=255, verbose_name='Modelo')),
                ('temperature', models.FloatField(default=0.7, verbose_name='Temperatura')),
                ('memory_config', models.JSONField(blank=True, default=dict, verbose_name='Configuração de Memória')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Agente',
                'verbose_name_plural': 'Agentes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('status', models.CharField(default='pending', max_length=50, verbose_name='Status')),
                ('input_data', models.JSONField(default=dict, verbose_name='Input')),
                ('output_data', models.JSONField(blank=True, default=dict, verbose_name='Output')),
                ('tokens_used', models.PositiveIntegerField(default=0, verbose_name='Tokens')),
                ('duration_ms', models.PositiveIntegerField(default=0, verbose_name='Duração')),
                ('error_message', models.TextField(blank=True, verbose_name='Erro')),
            ],
            options={
                'verbose_name': 'Execução de Agente',
                'verbose_name_plural': 'Execuções de Agentes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('code', models.CharField(max_length=255, unique=True, verbose_name='Código')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('handler_path', models.CharField(max_length=500, verbose_name='Handler Path')),
                ('input_schema', models.JSONField(blank=True, default=dict, verbose_name='Schema de Input')),
            ],
            options={
                'verbose_name': 'Ferramenta de Agente',
                'verbose_name_plural': 'Ferramentas de Agentes',
                'ordering': ['name'],
            },
        ),
    ]
