# Generated by Django 6.0.7 on 2026-07-27 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0001_initial'),
        ('ai', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agents', to='organizations.organization', verbose_name='Organização'),
        ),
        migrations.AddField(
            model_name='agent',
            name='provider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ai.aiproviderconfig', verbose_name='Provedor'),
        ),
        migrations.AddField(
            model_name='agentexecution',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='agents.agent', verbose_name='Agente'),
        ),
        migrations.AddField(
            model_name='agent',
            name='tools',
            field=models.ManyToManyField(blank=True, related_name='agents', to='agents.agenttool', verbose_name='Ferramentas'),
        ),
        migrations.AddIndex(
            model_name='agent',
            index=models.Index(fields=['organization', 'is_active'], name='agents_agen_organiz_09932e_idx'),
        ),
    ]
