# Generated by Django 6.0.7 on 2026-07-31 21:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('organizations', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('code', models.CharField(blank=True, max_length=60, verbose_name='Codigo interno')),
                ('description', models.TextField(blank=True, verbose_name='Descricao')),
                ('purpose', models.TextField(blank=True, verbose_name='Finalidade')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='Categoria')),
                ('color', models.CharField(blank=True, default='#2563eb', max_length=20, verbose_name='Cor')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('published', 'Publicado'), ('archived', 'Arquivado')], default='draft', max_length=20, verbose_name='Status')),
                ('instructions', models.TextField(blank=True, verbose_name='Instrucoes')),
                ('warning', models.TextField(blank=True, verbose_name='Aviso')),
                ('default_periodicity', models.CharField(blank=True, max_length=30, verbose_name='Periodicidade padrao')),
                ('variables', models.JSONField(blank=True, default=list, verbose_name='Variaveis')),
                ('stages', models.JSONField(blank=True, default=list, verbose_name='Etapas (rascunho)')),
                ('current_version', models.PositiveIntegerField(default=0, verbose_name='Versao atual publicada')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='templates', to='clients.department', verbose_name='Departamento')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='organizations.organization', verbose_name='Organização')),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_templates', to=settings.AUTH_USER_MODEL, verbose_name='Responsavel tecnico')),
            ],
            options={
                'verbose_name': 'Template',
                'verbose_name_plural': 'Templates',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='TemplateVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('version_number', models.PositiveIntegerField(verbose_name='Numero da versao')),
                ('name', models.CharField(max_length=255, verbose_name='Nome (no momento da publicacao)')),
                ('stages_snapshot', models.JSONField(default=list, verbose_name='Etapas (snapshot)')),
                ('metadata_snapshot', models.JSONField(blank=True, default=dict, verbose_name='Metadados (snapshot)')),
                ('is_current', models.BooleanField(default=True, verbose_name='E a versao vigente')),
                ('published_at', models.DateTimeField(auto_now_add=True, verbose_name='Publicado em')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='organizations.organization', verbose_name='Organização')),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_template_versions', to=settings.AUTH_USER_MODEL, verbose_name='Publicado por')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='radar_templates.template', verbose_name='Template')),
            ],
            options={
                'verbose_name': 'Versao de template',
                'verbose_name_plural': 'Versoes de template',
                'ordering': ['-version_number'],
            },
        ),
        migrations.CreateModel(
            name='TemplateApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('base_date', models.DateField(verbose_name='Data-base')),
                ('variables', models.JSONField(blank=True, default=dict, verbose_name='Variaveis informadas')),
                ('role_mappings', models.JSONField(blank=True, default=dict, verbose_name='Mapeamento de papeis/departamentos')),
                ('status', models.CharField(choices=[('active', 'Ativa'), ('completed', 'Concluida'), ('cancelled', 'Cancelada')], default='active', max_length=20, verbose_name='Status')),
                ('applied_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='template_applications_made', to=settings.AUTH_USER_MODEL, verbose_name='Aplicado por')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_applications', to='clients.clientcompany', verbose_name='Cliente')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='organizations.organization', verbose_name='Organização')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='radar_templates.template', verbose_name='Template')),
                ('template_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='radar_templates.templateversion', verbose_name='Versao aplicada')),
            ],
            options={
                'verbose_name': 'Aplicacao de template',
                'verbose_name_plural': 'Aplicacoes de template',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='template',
            index=models.Index(fields=['organization', 'status'], name='radar_templ_organiz_9069b7_idx'),
        ),
        migrations.AddIndex(
            model_name='template',
            index=models.Index(fields=['organization', 'category'], name='radar_templ_organiz_997ac9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='templateversion',
            unique_together={('template', 'version_number')},
        ),
        migrations.AddIndex(
            model_name='templateapplication',
            index=models.Index(fields=['organization', 'client'], name='radar_templ_organiz_90dbea_idx'),
        ),
        migrations.AddIndex(
            model_name='templateapplication',
            index=models.Index(fields=['organization', 'status'], name='radar_templ_organiz_c26705_idx'),
        ),
    ]
