# Generated by Django 6.0.7 on 2026-07-31 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('organizations', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('name', models.CharField(max_length=150, verbose_name='Nome')),
                ('date', models.DateField(verbose_name='Data')),
                ('recurring_yearly', models.BooleanField(default=False, verbose_name='Recorrente todo ano')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='organizations.organization', verbose_name='Organização')),
            ],
            options={
                'verbose_name': 'Feriado',
                'verbose_name_plural': 'Feriados',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('title', models.CharField(max_length=255, verbose_name='Titulo')),
                ('description', models.TextField(blank=True, verbose_name='Descricao')),
                ('start_date', models.DateTimeField(verbose_name='Inicio')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Fim')),
                ('all_day', models.BooleanField(default=False, verbose_name='Dia inteiro')),
                ('color', models.CharField(blank=True, max_length=20, verbose_name='Cor')),
                ('type', models.CharField(choices=[('meeting', 'Reuniao'), ('other', 'Outro')], default='meeting', max_length=20, verbose_name='Tipo')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calendar_events', to='clients.clientcompany', verbose_name='Cliente')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='organizations.organization', verbose_name='Organização')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['start_date'],
                'indexes': [models.Index(fields=['organization', 'start_date'], name='radar_calen_organiz_79dba5_idx')],
            },
        ),
    ]
