# Generated by Django 6.0.7 on 2026-07-27 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AICallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('provider_name', models.CharField(max_length=100, verbose_name='Provedor')),
                ('model', models.CharField(max_length=255, verbose_name='Modelo')),
                ('tokens_input', models.PositiveIntegerField(default=0, verbose_name='Tokens Input')),
                ('tokens_output', models.PositiveIntegerField(default=0, verbose_name='Tokens Output')),
                ('cost', models.DecimalField(decimal_places=6, default=0, max_digits=10, verbose_name='Custo')),
                ('latency_ms', models.PositiveIntegerField(default=0, verbose_name='Latência (ms)')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadados')),
            ],
            options={
                'verbose_name': 'Log de Chamada IA',
                'verbose_name_plural': 'Logs de Chamadas IA',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIModelConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('model_id', models.CharField(max_length=255, verbose_name='ID do Modelo')),
                ('display_name', models.CharField(max_length=255, verbose_name='Nome')),
                ('max_tokens', models.PositiveIntegerField(default=4096, verbose_name='Max Tokens')),
                ('cost_per_1k_input', models.DecimalField(decimal_places=6, default=0, max_digits=10, verbose_name='Custo/1k Input')),
                ('cost_per_1k_output', models.DecimalField(decimal_places=6, default=0, max_digits=10, verbose_name='Custo/1k Output')),
            ],
            options={
                'verbose_name': 'Configuração de Modelo IA',
                'verbose_name_plural': 'Configurações de Modelos IA',
            },
        ),
        migrations.CreateModel(
            name='AIProviderConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('provider_name', models.IntegerField(choices=[(1, 'OpenAI'), (2, 'Anthropic'), (3, 'Gemini')], verbose_name='Provedor')),
                ('display_name', models.CharField(max_length=255, verbose_name='Nome')),
                ('api_key_encrypted', models.BinaryField(blank=True, null=True, verbose_name='API Key')),
                ('models_list', models.JSONField(blank=True, default=dict, verbose_name='Modelos')),
                ('is_default', models.BooleanField(default=False, verbose_name='Padrão')),
            ],
            options={
                'verbose_name': 'Configuração de Provedor IA',
                'verbose_name_plural': 'Configurações de Provedores IA',
            },
        ),
    ]
