# Generated by Django 6.0.7 on 2026-07-27 22:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai', '0002_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aicalllog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_call_logs', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AddField(
            model_name='aiproviderconfig',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_providers', to='organizations.organization', verbose_name='Organização'),
        ),
        migrations.AddField(
            model_name='aimodelconfig',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='ai.aiproviderconfig', verbose_name='Provedor'),
        ),
        migrations.AddIndex(
            model_name='aicalllog',
            index=models.Index(fields=['organization', '-created_at'], name='ai_aicalllo_organiz_d189c0_idx'),
        ),
        migrations.AddIndex(
            model_name='aicalllog',
            index=models.Index(fields=['provider_name', 'model'], name='ai_aicalllo_provide_c57e4e_idx'),
        ),
        migrations.AddIndex(
            model_name='aiproviderconfig',
            index=models.Index(fields=['provider_name', 'is_default'], name='ai_aiprovid_provide_d275ae_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='aimodelconfig',
            unique_together={('model_id', 'provider')},
        ),
    ]
