# Generated by Django 6.0.7 on 2026-07-28 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('steps_config', models.JSONField(blank=True, default=list, verbose_name='Configuração de Etapas')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflows', to='organizations.organization', verbose_name='Organização')),
            ],
            options={
                'verbose_name': 'Workflow',
                'verbose_name_plural': 'Workflows',
            },
        ),
        migrations.CreateModel(
            name='WorkflowExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('status', models.IntegerField(choices=[(1, 'Pendente'), (2, 'Em execução'), (3, 'Concluído'), (4, 'Falhou'), (5, 'Pausado'), (6, 'Cancelado')], default=1, verbose_name='Status')),
                ('current_step', models.PositiveIntegerField(default=0, verbose_name='Etapa Atual')),
                ('input_data', models.JSONField(default=dict, verbose_name='Input')),
                ('output_data', models.JSONField(blank=True, default=dict, verbose_name='Output')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Início')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Conclusão')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='workflows.workflow', verbose_name='Workflow')),
            ],
            options={
                'verbose_name': 'Execução de Workflow',
                'verbose_name_plural': 'Execuções de Workflows',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowStepLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_name', models.CharField(max_length=255, verbose_name='Nome da Etapa')),
                ('status', models.CharField(max_length=50, verbose_name='Status')),
                ('input_data', models.JSONField(default=dict, verbose_name='Input')),
                ('output_data', models.JSONField(blank=True, default=dict, verbose_name='Output')),
                ('error_message', models.TextField(blank=True, verbose_name='Erro')),
                ('duration_ms', models.PositiveIntegerField(default=0, verbose_name='Duração')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_logs', to='workflows.workflowexecution', verbose_name='Execução')),
            ],
            options={
                'verbose_name': 'Log de Etapa',
                'verbose_name_plural': 'Logs de Etapas',
                'ordering': ['created_at'],
            },
        ),
    ]
