# Generated by Django 6.0.7 on 2026-07-31 21:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('organizations', '0002_initial'),
        ('radar_tasks', '0001_initial'),
        ('storage', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('title', models.CharField(max_length=255, verbose_name='Titulo')),
                ('instructions', models.TextField(blank=True, verbose_name='Instrucoes')),
                ('due_date', models.DateTimeField(blank=True, null=True, verbose_name='Prazo')),
                ('accepted_formats', models.CharField(blank=True, max_length=255, verbose_name='Formatos aceitos')),
                ('reminder_1d', models.BooleanField(default=False)),
                ('reminder_3d', models.BooleanField(default=False)),
                ('reminder_7d', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('solicitado', 'Solicitado'), ('recebido', 'Recebido')], default='solicitado', max_length=20, verbose_name='Status')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_requests', to='clients.clientcompany', verbose_name='Cliente')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='organizations.organization', verbose_name='Organização')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_requests_made', to=settings.AUTH_USER_MODEL, verbose_name='Solicitado por')),
            ],
            options={
                'verbose_name': 'Solicitacao de documento',
                'verbose_name_plural': 'Solicitacoes de documento',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='Categoria')),
                ('allowed_formats', models.CharField(blank=True, max_length=255, verbose_name='Formatos aceitos')),
                ('max_size_mb', models.PositiveIntegerField(default=25, verbose_name='Tamanho maximo (MB)')),
                ('validity_days', models.PositiveIntegerField(blank=True, null=True, verbose_name='Prazo de validade (dias)')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='organizations.organization', verbose_name='Organização')),
            ],
            options={
                'verbose_name': 'Tipo de documento',
                'verbose_name_plural': 'Tipos de documento',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('status', models.CharField(choices=[('solicitado', 'Solicitado'), ('recebido', 'Recebido'), ('em_análise', 'Em analise'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado'), ('arquivado', 'Arquivado')], default='recebido', max_length=20, verbose_name='Status')),
                ('competence', models.CharField(blank=True, max_length=20, verbose_name='Competencia')),
                ('validity_date', models.DateField(blank=True, null=True, verbose_name='Validade')),
                ('notes', models.TextField(blank=True, verbose_name='Observacoes')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Motivo da rejeicao')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='clients.clientcompany', verbose_name='Cliente')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='organizations.organization', verbose_name='Organização')),
                ('stored_object', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='storage.storedobject', verbose_name='Arquivo')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_documents', to='radar_tasks.task', verbose_name='Tarefa vinculada')),
                ('request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fulfillments', to='radar_documents.documentrequest', verbose_name='Solicitacao de origem')),
                ('document_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='radar_documents.documenttype', verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='documentrequest',
            index=models.Index(fields=['organization', 'client', 'status'], name='radar_docum_organiz_0df97f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='documenttype',
            unique_together={('organization', 'name')},
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['organization', 'client', 'status'], name='radar_docum_organiz_031ebd_idx'),
        ),
    ]
