# Generated by Django 6.0.7 on 2026-07-31 21:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('name', models.CharField(max_length=60, verbose_name='Nome')),
                ('color', models.CharField(blank=True, default='#6b7280', max_length=20, verbose_name='Cor')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='organizations.organization', verbose_name='Organização')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['name'],
                'unique_together': {('organization', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ClientCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Deletado')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deletado em')),
                ('name', models.CharField(max_length=255, verbose_name='Razão social')),
                ('trade_name', models.CharField(blank=True, max_length=255, verbose_name='Nome fantasia')),
                ('cnpj', models.CharField(blank=True, max_length=18, verbose_name='CNPJ')),
                ('ie', models.CharField(blank=True, max_length=30, verbose_name='Inscrição estadual')),
                ('im', models.CharField(blank=True, max_length=30, verbose_name='Inscrição municipal')),
                ('cnae', models.CharField(blank=True, max_length=20, verbose_name='CNAE principal')),
                ('tax_regime', models.CharField(blank=True, max_length=60, verbose_name='Regime tributário')),
                ('company_size', models.CharField(blank=True, max_length=30, verbose_name='Porte')),
                ('segment', models.CharField(blank=True, max_length=100, verbose_name='Segmento')),
                ('open_date', models.DateField(blank=True, null=True, verbose_name='Data de abertura')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('active', 'Ativo'), ('suspended', 'Suspenso'), ('archived', 'Arquivado')], default='active', max_length=20, verbose_name='Status')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Telefone')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Endereço')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Cidade')),
                ('state', models.CharField(blank=True, max_length=2, verbose_name='UF')),
                ('zip_code', models.CharField(blank=True, max_length=10, verbose_name='CEP')),
                ('notes', models.TextField(blank=True, verbose_name='Observações internas')),
                ('portal_access', models.BooleanField(default=False, verbose_name='Acesso ao portal')),
                ('service_start_date', models.DateField(blank=True, null=True, verbose_name='Início do atendimento')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='organizations.organization', verbose_name='Organização')),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_clients', to=settings.AUTH_USER_MODEL, verbose_name='Responsável')),
                ('tags', models.ManyToManyField(blank=True, related_name='clients', to='clients.tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Empresa-cliente',
                'verbose_name_plural': 'Empresas-clientes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('name', models.CharField(max_length=150, verbose_name='Nome')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Telefone')),
                ('role', models.CharField(blank=True, max_length=100, verbose_name='Cargo')),
                ('has_portal_access', models.BooleanField(default=False, verbose_name='Acesso ao portal')),
                ('password_hash', models.CharField(blank=True, max_length=255, verbose_name='Senha do portal (hash)')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='clients.clientcompany', verbose_name='Cliente')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='organizations.organization', verbose_name='Organização')),
            ],
            options={
                'verbose_name': 'Contato do cliente',
                'verbose_name_plural': 'Contatos do cliente',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['client'], name='clients_cli_client__3e31d3_idx')],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('color', models.CharField(blank=True, default='#2563eb', max_length=20, verbose_name='Cor')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_departments', to=settings.AUTH_USER_MODEL, verbose_name='Gestor')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='organizations.organization', verbose_name='Organização')),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
                'ordering': ['name'],
                'unique_together': {('organization', 'name')},
            },
        ),
        migrations.AddIndex(
            model_name='clientcompany',
            index=models.Index(fields=['organization', 'status'], name='clients_cli_organiz_c1dfaa_idx'),
        ),
        migrations.AddIndex(
            model_name='clientcompany',
            index=models.Index(fields=['organization', 'cnpj'], name='clients_cli_organiz_60c69a_idx'),
        ),
        migrations.AddIndex(
            model_name='clientcompany',
            index=models.Index(fields=['organization', 'name'], name='clients_cli_organiz_91c565_idx'),
        ),
    ]
