# Generated by Django 6.0.7 on 2026-07-28 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsAggregation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.DateField(verbose_name='Período')),
                ('module', models.CharField(max_length=100, verbose_name='Módulo')),
                ('metric', models.CharField(max_length=255, verbose_name='Métrica')),
                ('value', models.DecimalField(decimal_places=6, default=0, max_digits=20, verbose_name='Valor')),
            ],
            options={
                'verbose_name': 'Agregação de Analytics',
                'verbose_name_plural': 'Agregações de Analytics',
            },
        ),
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('event_type', models.CharField(max_length=255, verbose_name='Tipo')),
                ('module', models.CharField(max_length=100, verbose_name='Módulo')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadados')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
            ],
            options={
                'verbose_name': 'Evento de Analytics',
                'verbose_name_plural': 'Eventos de Analytics',
                'ordering': ['-timestamp'],
            },
        ),
    ]
