# Generated by Django 6.0.7 on 2026-07-28 13:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='analyticsevent',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AlterUniqueTogether(
            name='analyticsaggregation',
            unique_together={('organization', 'period', 'module', 'metric')},
        ),
        migrations.AddIndex(
            model_name='analyticsevent',
            index=models.Index(fields=['organization', 'event_type', 'timestamp'], name='analytics_a_organiz_153523_idx'),
        ),
    ]
