# Generated by Django 6.0.7 on 2026-07-28 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255, unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('module', models.CharField(max_length=100, verbose_name='Módulo')),
            ],
            options={
                'verbose_name': 'Permissão',
                'verbose_name_plural': 'Permissões',
                'ordering': ['module', 'code'],
                'indexes': [models.Index(fields=['code'], name='permissions_code_cd9166_idx'), models.Index(fields=['module'], name='permissions_module_ebdb5f_idx')],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('is_default', models.BooleanField(default=False, verbose_name='Papel padrão')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='organizations.organization', verbose_name='Organização')),
            ],
            options={
                'verbose_name': 'Papel',
                'verbose_name_plural': 'Papéis',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='permissions.permission', verbose_name='Permissão')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='permissions.role', verbose_name='Papel')),
            ],
            options={
                'verbose_name': 'Permissão do Papel',
                'verbose_name_plural': 'Permissões do Papel',
                'unique_together': {('role', 'permission')},
            },
        ),
        migrations.AddField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(blank=True, related_name='roles', through='permissions.RolePermission', to='permissions.permission', verbose_name='Permissões'),
        ),
        migrations.AlterUniqueTogether(
            name='role',
            unique_together={('name', 'organization')},
        ),
    ]
