# Generated by Django 6.0.7 on 2026-07-28 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StorageBackendConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('backend_type', models.IntegerField(choices=[(1, 'AWS S3'), (2, 'MinIO'), (3, 'Cloudflare R2'), (4, 'Local')], verbose_name='Tipo')),
                ('config_encrypted', models.BinaryField(blank=True, null=True, verbose_name='Configuração')),
                ('is_default', models.BooleanField(default=False, verbose_name='Padrão')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='storage_configs', to='organizations.organization', verbose_name='Organização')),
            ],
            options={
                'verbose_name': 'Configuração de Storage',
                'verbose_name_plural': 'Configurações de Storage',
            },
        ),
        migrations.CreateModel(
            name='StoredObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('key', models.CharField(max_length=1000, verbose_name='Chave')),
                ('bucket', models.CharField(max_length=255, verbose_name='Bucket')),
                ('size', models.PositiveBigIntegerField(default=0, verbose_name='Tamanho')),
                ('content_type', models.CharField(max_length=255, verbose_name='Content Type')),
                ('checksum', models.CharField(blank=True, max_length=255, verbose_name='Checksum')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadados')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stored_objects', to='organizations.organization', verbose_name='Organização')),
            ],
            options={
                'verbose_name': 'Objeto Armazenado',
                'verbose_name_plural': 'Objetos Armazenados',
                'ordering': ['-created_at'],
            },
        ),
    ]
