# Generated by Django 6.0.7 on 2026-07-27 22:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('storage', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='storedobject',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Uploaded by'),
        ),
        migrations.AddIndex(
            model_name='storedobject',
            index=models.Index(fields=['organization', 'key'], name='storage_sto_organiz_d46f0d_idx'),
        ),
    ]
