# Generated by Django 6.0.7 on 2026-07-27 22:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('role', models.IntegerField(choices=[(1, 'Proprietário'), (2, 'Administrador'), (3, 'Membro'), (4, 'Visualizador')], default=3, verbose_name='Papel')),
                ('token', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='Token')),
                ('accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='Aceito em')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Expira em')),
                ('status', models.IntegerField(choices=[(1, 'Pendente'), (2, 'Aceito'), (3, 'Recusado'), (4, 'Expirado')], default=1, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Convite',
                'verbose_name_plural': 'Convites',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('role', models.IntegerField(choices=[(1, 'Proprietário'), (2, 'Administrador'), (3, 'Membro'), (4, 'Visualizador')], default=3, verbose_name='Papel')),
                ('status', models.IntegerField(choices=[(1, 'Ativo'), (2, 'Inativo'), (3, 'Pendente'), (4, 'Suspenso')], default=1, verbose_name='Status')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='Entrou em')),
            ],
            options={
                'verbose_name': 'Membro',
                'verbose_name_plural': 'Membros',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
                ('status', models.IntegerField(choices=[(1, 'Ativo'), (2, 'Inativo'), (3, 'Pendente'), (4, 'Suspenso')], default=1, verbose_name='Status')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadados')),
            ],
            options={
                'verbose_name': 'Organização',
                'verbose_name_plural': 'Organizações',
                'ordering': ['-created_at'],
            },
        ),
    ]
