# Generated by Django 6.0.7 on 2026-07-31 23:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('organizations', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='clients.department', verbose_name='Departamento'),
        ),
    ]
