# Generated by Django 6.0.7 on 2026-07-27 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notifications', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationchannel',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_channels', to='organizations.organization', verbose_name='Organização'),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='channel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='notifications.notificationchannel', verbose_name='Canal'),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='notifications.notificationtemplate', verbose_name='Template'),
        ),
    ]
