# Generated by Django 6.0.7 on 2026-08-01 00:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_initial'),
        ('organizations', '0003_membership_department'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('message', models.TextField(blank=True, verbose_name='Mensagem')),
                ('type', models.CharField(default='info', max_length=50, verbose_name='Tipo')),
                ('priority', models.CharField(default='normal', max_length=20, verbose_name='Prioridade')),
                ('link', models.CharField(blank=True, max_length=500, verbose_name='Link')),
                ('read', models.BooleanField(default=False, verbose_name='Lida')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Lida em')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inapp_notifications', to='organizations.organization', verbose_name='Organização')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': 'Notificações',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'read'], name='notificatio_user_id_878a13_idx')],
            },
        ),
    ]
